### PR TITLE
Use setWrappedHtmlBody() for html emails.

### PR DESCRIPTION
**Pull request by diosmosis**
Refs https://github.com/matomo-org/matomo/pull/13908

### CODE REVIEW

**Comment by tsteur** [comment]
Looks good. I reckon we need to increase the required Matomo version in plugin.json?

**Comment by diosmosis** [comment]
Good point, will do.

**Comment by diosmosis** [comment]
Actually, not sure what to set it to yet, so will hold off. Will https://github.com/matomo-org/matomo/pull/13908 be merged for 3.8? or should we wait for 3.9?

**Comment by tsteur** [comment]
I reckon 3.8

**Comment by diosmosis** [comment]
Updated plugin.json (for CustomAlerts as well)

**Pull request merged**
